config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :plantings


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/harvest.rb
class Harvest < ApplicationRecord
  belongs_to :planting
  belongs_to :user
end

app/models/planting.rb
class Planting < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :harvests
  scope :mine, ->(user) { where(user: user) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :harvests
  #  enum status: { picker: 1, owner: 2 }

  #  validates :photo, allow_blank:false
  #validates :position,
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
#  include Pundit

#  after_action :verify_authorized, except: :index, unless: :skip_pundit?
#  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :gender])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  private

  def skip_pundit?
#    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/plantings_controller.rb
class PlantingsController < ApplicationController

  def new
    @planting = Planting.new
  end

  def create
  @planting = Planting.new(planting_params)
  owner = current_user
    if @planting.save
      redirect_to plantings_path
    else
      render :new
     end
  end

  def index
    @plantings = Planting.all
  end

  def show
    @planting =Planting.find(params[:id])
  end

  def edit
    @planting = Planting.find(params[:id])
  end

  def update
    @planting = Planting.find(params[:id])
    @planting.update(planting_params)
    redirect_to plantings_path
  end

  def destroy
    @planting = Planting.find(params[:id])
    @planting.destroy
  end

  private

  def planting_params
    params.require(:planting).permit(:name, :description, :price, :price_kind, :address, :photo)
  end

end

app/controllers/user_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    @user.save
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :status, :age, :gender, :photo, :address)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <img url('home-tree.jpg')>
  <div class="home-container">
    <div class="home-title">
      <h1>PICK MY FRUITS</h1>
    </div>
      <p class="home-subtitle">Imagine your city as the biggest garden ever...</p>
      <p class="home-subtitle">What would you do?</p>
      <p class="btn first-choice-button">Go for picking!</p>
      <div>
        <%= link_to 'watch all my plantings', plantings_path %>
      </div>
      <div>
        <%= link_to 'Share a new planting', new_planting_path %> </p>
      </div>
  </div>
</div>

app/views/plantings/_form_edit_planting.erb
  <%= simple_form_for(@planting) do |f| %>
    <%= f.input :name %>
    <%= f.input :category %>
    <%= f.input :price %>
    <%= f.input :price_kind %>
    <%= f.input :description %>
    <%= f.input :address %>
    <%= f.input :photo %>
    <%= f.submit "Update my Planting", class: "btn btn-success" %>
  <% end %>

app/views/plantings/_form_new_planting.erb
  <%= simple_form_for(@planting) do |f| %>
    <%= f.input :name %>
    <%= f.input :category %>
    <%= f.input :price %>
    <%= f.input :price_kind %>
    <%= f.input :description %>
    <%= f.input :address %>
    <%= f.input :photo %>
    <%= f.submit "Add my Planting", class: "btn btn-success" %>
  <% end %>

app/views/plantings/edit.erb
<%= render 'form_edit_planting', planting: @planting, method: :post %>

app/views/plantings/index.html.erb
<h1>Choose and pick the fruits!</h1>
<ul class="list-inline">
  <% @plantings.each do |planting| %>
    <% if current_user == planting.user %>
      <%= link_to planting.name, planting_path(planting), class: "conv-link" %>
      <p><%="#{planting.price} / #{planting.price_kind}"%></p>
    <% end %>
  <% end %>
</ul>

app/views/plantings/new.html.erb
<h1>Post your Fruit, get your garden clean & earn money!</h1>
<%= render 'form_new_planting', method: :post %>

app/views/plantings/show.html.erb
<p><%= @planting.photo %></p>
<%=link_to "", edit_planting_path(@planting), class: "fas fa-edit" %>
<p>Planting: <%= @planting.name %></p>
<p>Category: <%= @planting.category %></p>
<p>Price: <%= "#{@planting.price}€ / #{@planting.price_kind}" %></p>
<p>Description: <%= @planting.description %></p>
<p>Address: <%= @planting.address %></p>
<p>Last update: <%= @planting.updated_at %></p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-fruit">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-fruit-brand" do %>
    <%= image_tag "logo.jpg", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-fruit-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <!-- Avatar with dropdown menu -->
      <div class="navbar-fruit-item">
        <div class="dropdown">
          <%= image_tag "https://m.media-amazon.com/images/M/MV5BMDFmNDg5YzYtZjM3Ny00MjY3LThlYjctNTJlMTJmYWFhMzBkL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjk4NTU4NTI@._V1_.jpg", class: "avatar dropdown-toggle", id: "navbar-fruit-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-fruit-dropdown-menu">
            <li>
              <%= link_to "user." do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-fruit-item navbar-fruit-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-fruit-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-fruit-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>